
export const TODO_LIST_CREATE_REQUEST = 'TODO_LIST_CREATE_REQUEST';
export const TODO_LIST_CREATE_SUCCESS = 'TODO_LIST_CREATE_SUCCESS';
export const TODO_LIST_CREATE_FAIL = 'TODO_LIST_CREATE_FAIL';
export const TODO_LIST_CREATE_RESET = 'TODO_LIST_CREATE_RESET';

export const TODO_LIST_GET_REQUEST = 'TODO_LIST_GET_REQUEST';
export const TODO_LIST_GET_SUCCESS = 'TODO_LIST_GET_SUCCESS';
export const TODO_LIST_GET_FAIL = 'TODO_LIST_GET_FAIL';

export const TODO_LIST_UPDATE_REQUEST = 'TODO_LIST_UPDATE_REQUEST';
export const TODO_LIST_UPDATE_SUCCESS = 'TODO_LIST_UPDATE_SUCCESS';
export const TODO_LIST_UPDATE_FAIL = 'TODO_LIST_UPDATE_FAIL';
export const TODO_LIST_UPDATE_RESET = 'TODO_LIST_UPDATE_RESET';

export const TODO_LIST_DELETE_REQUEST = 'TODO_LIST_DELETE_REQUEST';
export const TODO_LIST_DELETE_SUCCESS = 'TODO_LIST_DELETE_SUCCESS';
export const TODO_LIST_DELETE_FAIL = 'TODO_LIST_DELETE_FAIL';



